version: "3"

services:
  app:
    container_name: perna.in
    restart: always
    build: .
    volumes:
      - .:/code
    env_file:
     - ./.env
    environment:
     - NODE_ENV=development
    ports:
      - "3000:3001"
    links:
      - mongo
    depends_on:
      - mongo
    command: npx nodemon npm start

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
